version: '3.8'

services:
  java-api:
    build:
      context: ./java-api
      dockerfile: Dockerfile
    container_name: wunsen-java-api
    ports:
      - "4060:4060"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=4060
    networks:
      - wunsen-network
    restart: unless-stopped

  go-api:
    build:
      context: ./go-api
      dockerfile: Dockerfile
    container_name: wunsen-go-api
    ports:
      - "4000:4000"
    environment:
      - GO_ENV=production
      - PORT=4000
      - JAVA_API_URL=http://wunsen-java-api:4060
    networks:
      - wunsen-network
    restart: unless-stopped
    depends_on:
      - java-api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wunsen-network:
    driver: bridge

volumes:
  go-api-data:
  java-api-data: